blank_issues_enabled: true
contact_links:
  - name: ğŸ“– Documentation
    url: https://doc.ecole.ai/
    about: Find common usage in the documentation.
  - name: â“ Github Discussions
    url: https://github.com/ds4dm/ecole/discussions
    about: Ask questions and share ideas.
